### Create a conference entity
POST http://0.0.0.0:9000/conferences/kubecon
Content-Type: application/json

{
  "name": "kubecon",
  "deadline": "2023-12-14"
}

###  Create a second one entity
POST http://0.0.0.0:9000/conferences/scaladays
Content-Type: application/json

{
  "name": "Scala Days",
  "deadline": "2024-01-11"
}

###
GET http://0.0.0.0:9000/conferences/kubecon

### List all conferences view
GET http://0.0.0.0:9000/conferences

### create a entity by calling the api
POST http://0.0.0.0:9000/api/slack/conferences/create?text=scalaconf%202023-12-14


### create a entity by calling the api
POST http://0.0.0.0:9000/api/slack/conferences/create
Content-Type: application/x-www-form-urlencoded

text=scalaconf%202023-12-14

### create a entity by calling the api
POST https://snowy-rain-0581.us-east-2.kalixapps.com/api/slack/conferences/create
Content-Type: application/x-www-form-urlencoded

text = scalaconf%202023-12-14